### ISSUE TITLE
dummy data files described on wiki

### ISSUE THREAD

**Issue by swise5** [dime-worldbank/Disease-Modelling-SSA#22]
the wiki would benefit from more information about the data files. The basic required files are now in the `main` branch under `Protecs/src/main/resources`, and it would be great to have the information about whence might come such data (either in our existing workflow or in other workflows that might use the same tool in the future)

**Comment by RobertManningSmith** [comment]
Double check that all dummy files are mentioned

**Comment by RobertManningSmith** [comment]
All files are mentioned in the WIKI can close this issue
